spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou


server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka